"""empty message

Revision ID: 788ff78c6716
Revises: 94ce88e5cbae
Create Date: 2020-08-07 15:47:17.706166

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '788ff78c6716'
down_revision = '94ce88e5cbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'post', ['id'])
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'password')
    op.drop_constraint(None, 'post', type_='unique')
    # ### end Alembic commands ###
